db.encrypt_key=bngSys
#IC_primary
db.host_primary_ic=ENC(vqCjqeMHr6xCDeSjzjhAxmTIS7GLJc6r)
#IC_secondary
db.host_secondary_ic=ENC(zEqxRLvlfqPHgGqBukFe0XgMVf05At1K)
#m11_primary
db.host_primary_m11=ENC(CCCLeTw7eAGgolxo2xMAMfeyWFjneQ/9)
#m11_secondary
db.host_secondary_m11=ENC(oZMKBz5ms0RZRyFOVQga9Zl2ZVRa5f3Q)
#m15_primary
db.host_primary_m15=ENC(GwhX7KPsgSjyRzv7L6ksPu2V75pj6ZJb)
#m15_secondary
db.host_secondary_m15=ENC(jKElTXBx/sRYCaPh/5zvs6aq4QgsvRTx)
#wuxi 121
db.host_primary_c2=ENC(yzT6W3bQORSMvSIJJv31qnFmoaiWO1Q6)
#wuxi 122
db.host_secondary_c2=ENC(VgWYRTc1g7n5CU1k4GxBsOgcbspGpyhn)
#wuxi 123
db.host_third_c2=ENC(AyodG31AUTcVD/7cd3gyMWY/bV0tiU0/)

db.pw=ENC(0pDZHCTr2KGPBVRUABYRxEDvxlPT49jm)