# function reset
# "TRY" ---> reset will be start | "DONE" ---> reset finished
# !!! if you modify the content to `TRY`, wait until the modified content is `DONE` !!!
M14A.A.HID_OFF=DONE
M14A.A.VHL_OFF=DONE
M14A.A.RAIL_CUT=DONE
M14A.A.VHL_CNT=DONE