#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
raw_columns — aws_idc_realtime_collector.py 의 265개 IDC 컬럼 + 룰베이스 매핑 정리
===================================================================================
- 발동이벤트.csv reason / 사건단위.csv relation 을 보고 → 어떤 raw 풀네임 컬럼이 발동했는지 식별
- 발동이벤트.csv 의 축약 컬럼명 (예: M16HUB_ra) ↔ raw 풀네임 (M16HUB.QUE.TIME.AVGTOTALTIME1MIN) 양방향 매핑

이 모듈은 DB 접속 안 함. reason/relation 텍스트만 보고 컬럼 식별.

사용:
  from raw_columns import (
      RAW_COLS_265,           # 265개 IDC 컬럼 리스트
      RA_COL, RB_COL,          # 영역별 raw 컬럼 매핑
      RD_OHT_COL, SLA_COL, SORTER_COL,
      RD_FAB_COL, RD_STB_COL,
      EVT_TO_RAW, RAW_TO_EVT,  # 축약 ↔ 풀네임 양방향
      parse_reason_pairs,      # reason → [(evt_col, raw_full, area, rule), ...]
      parse_relation_pairs,    # relation → 동일
  )
"""
import re

# ============================================================
# ★ aws_idc_realtime_collector.py 의 IDC_COLUMNS 265개 (v4.1 전체)
# ============================================================
RAW_COLS_265 = [
    # ── M16HUB (110개) ──
    "M16HUB.CNV.SENDFAB.TO_M14A_CURRENTQCNT",
    "M16HUB.LFT.6ABL0111.2F_TO_3F_CURRENTQCNT", "M16HUB.LFT.6ABL0111.2F_TO_6F_CURRENTQCNT",
    "M16HUB.LFT.6ABL0111.3F_TO_2F_CURRENTQCNT", "M16HUB.LFT.6ABL0111.3F_TO_6F_CURRENTQCNT",
    "M16HUB.LFT.6ABL0111.6F_TO_2F_CURRENTQCNT", "M16HUB.LFT.6ABL0111.6F_TO_3F_CURRENTQCNT",
    "M16HUB.LFT.6ABL0111.TOTAL_CURRENTQCNT",
    "M16HUB.LFT.6ABL0112.2F_TO_3F_CURRENTQCNT", "M16HUB.LFT.6ABL0112.2F_TO_6F_CURRENTQCNT",
    "M16HUB.LFT.6ABL0112.3F_TO_2F_CURRENTQCNT", "M16HUB.LFT.6ABL0112.3F_TO_6F_CURRENTQCNT",
    "M16HUB.LFT.6ABL0112.6F_TO_2F_CURRENTQCNT", "M16HUB.LFT.6ABL0112.6F_TO_3F_CURRENTQCNT",
    "M16HUB.LFT.6ABL0112.TOTAL_CURRENTQCNT",
    "M16HUB.LFT.6ABL0121.2F_TO_3F_CURRENTQCNT", "M16HUB.LFT.6ABL0121.2F_TO_6F_CURRENTQCNT",
    "M16HUB.LFT.6ABL0121.3F_TO_2F_CURRENTQCNT", "M16HUB.LFT.6ABL0121.3F_TO_6F_CURRENTQCNT",
    "M16HUB.LFT.6ABL0121.6F_TO_2F_CURRENTQCNT", "M16HUB.LFT.6ABL0121.TOTAL_CURRENTQCNT",
    "M16HUB.LFT.6ABL0122.2F_TO_6F_CURRENTQCNT", "M16HUB.LFT.6ABL0122.3F_TO_2F_CURRENTQCNT",
    "M16HUB.LFT.6ABL0122.3F_TO_6F_CURRENTQCNT", "M16HUB.LFT.6ABL0122.6F_TO_2F_CURRENTQCNT",
    "M16HUB.LFT.6ABL0122.6F_TO_3F_CURRENTQCNT", "M16HUB.LFT.6ABL0122.TOTAL_CURRENTQCNT",
    "M16HUB.LFT.6ABL6011.2F_TO_3F_CURRENTQCNT", "M16HUB.LFT.6ABL6011.2F_TO_6F_CURRENTQCNT",
    "M16HUB.LFT.6ABL6011.3F_TO_2F_CURRENTQCNT", "M16HUB.LFT.6ABL6011.6F_TO_2F_CURRENTQCNT",
    "M16HUB.LFT.6ABL6011.6F_TO_3F_CURRENTQCNT", "M16HUB.LFT.6ABL6011.TOTAL_CURRENTQCNT",
    "M16HUB.LFT.6ABL6012.2F_TO_3F_CURRENTQCNT", "M16HUB.LFT.6ABL6012.2F_TO_6F_CURRENTQCNT",
    "M16HUB.LFT.6ABL6012.3F_TO_2F_CURRENTQCNT", "M16HUB.LFT.6ABL6012.3F_TO_6F_CURRENTQCNT",
    "M16HUB.LFT.6ABL6012.6F_TO_2F_CURRENTQCNT", "M16HUB.LFT.6ABL6012.6F_TO_3F_CURRENTQCNT",
    "M16HUB.LFT.6ABL6012.TOTAL_CURRENTQCNT",
    "M16HUB.LFT.6ABL6021.2F_TO_3F_CURRENTQCNT", "M16HUB.LFT.6ABL6021.2F_TO_6F_CURRENTQCNT",
    "M16HUB.LFT.6ABL6021.3F_TO_2F_CURRENTQCNT", "M16HUB.LFT.6ABL6021.3F_TO_6F_CURRENTQCNT",
    "M16HUB.LFT.6ABL6021.6F_TO_2F_CURRENTQCNT", "M16HUB.LFT.6ABL6021.6F_TO_3F_CURRENTQCNT",
    "M16HUB.LFT.6ABL6021.TOTAL_CURRENTQCNT",
    "M16HUB.LFT.6ABL6022.2F_TO_3F_CURRENTQCNT", "M16HUB.LFT.6ABL6022.2F_TO_6F_CURRENTQCNT",
    "M16HUB.LFT.6ABL6022.3F_TO_2F_CURRENTQCNT", "M16HUB.LFT.6ABL6022.3F_TO_6F_CURRENTQCNT",
    "M16HUB.LFT.6ABL6022.6F_TO_2F_CURRENTQCNT", "M16HUB.LFT.6ABL6022.6F_TO_3F_CURRENTQCNT",
    "M16HUB.LFT.6ABL6022.TOTAL_CURRENTQCNT",
    "M16HUB.LFT.6ABL6031.2F_TO_3F_CURRENTQCNT", "M16HUB.LFT.6ABL6031.2F_TO_6F_CURRENTQCNT",
    "M16HUB.LFT.6ABL6031.3F_TO_2F_CURRENTQCNT", "M16HUB.LFT.6ABL6031.3F_TO_6F_CURRENTQCNT",
    "M16HUB.LFT.6ABL6031.6F_TO_2F_CURRENTQCNT", "M16HUB.LFT.6ABL6031.6F_TO_3F_CURRENTQCNT",
    "M16HUB.LFT.6ABL6031.TOTAL_CURRENTQCNT",
    "M16HUB.LFT.6ABL6032.2F_TO_3F_CURRENTQCNT", "M16HUB.LFT.6ABL6032.3F_TO_2F_CURRENTQCNT",
    "M16HUB.LFT.6ABL6032.3F_TO_6F_CURRENTQCNT", "M16HUB.LFT.6ABL6032.6F_TO_2F_CURRENTQCNT",
    "M16HUB.LFT.6ABL6032.6F_TO_3F_CURRENTQCNT", "M16HUB.LFT.6ABL6032.TOTAL_CURRENTQCNT",
    "M16HUB.LFT.SENDFAB.TO_M14B_CURRENTQCNT", "M16HUB.LFT.SENDFAB.TO_M16A_CURRENTQCNT",
    "M16HUB.LFT.SENDFAB.TO_M16E_CURRENTQCNT",
    "M16HUB.OHT.ALERT.OHTMCPALARMCNT",
    "M16HUB.QUE.ABN.AOTRANSDELAY",
    "M16HUB.QUE.ALL.3F_CMD", "M16HUB.QUE.ALL.3F_TO_3F_MLUD_JOB",
    "M16HUB.QUE.ALL.3F_TO_M14A_3F_JOB", "M16HUB.QUE.ALL.3F_TO_M14B_7F_JOB",
    "M16HUB.QUE.ALL.3F_TO_M16A_2F_JOB", "M16HUB.QUE.ALL.3F_TO_M16A_6F_JOB",
    "M16HUB.QUE.ALL.CURRENTQCNT", "M16HUB.QUE.ALL.CURRENTQCOMPLETED",
    "M16HUB.QUE.ALL.CURRENTQCREATED",
    "M16HUB.QUE.ALL.CURRENT_M16A_3F_JOB", "M16HUB.QUE.ALL.CURRENT_M16A_3F_JOB_2",
    "M16HUB.QUE.ALL.FABTRANSJOBCNT",
    "M16HUB.QUE.ALL.M16HUBTOM14MANUAL_CURRENTQCNT",
    "M16HUB.QUE.ALL.TRANSPORT4MINOVERCNT", "M16HUB.QUE.ALL.TRANSPORT4MINOVERRATIO",
    "M16HUB.QUE.ALL.TRANSPORT4MINOVERTIMEAVG",
    "M16HUB.QUE.CNV.3F_CNV_MAXCAPA", "M16HUB.QUE.CNV.3F_TO_M14A_CNV_AI_CMD",
    "M16HUB.QUE.LFT.3F_LFT_MAXCAPA", "M16HUB.QUE.LFT.3F_M14BLFT_MAXCAPA",
    "M16HUB.QUE.LFT.3F_TO_M14B_LFT_AI_CMD", "M16HUB.QUE.LFT.3F_TO_M16A_LFT_AI_CMD",
    "M16HUB.QUE.LOAD.AVGLOADTIME",
    "M16HUB.QUE.M14ATOM16.MESCURRENTQCNT", "M16HUB.QUE.M14BTOM16.MESCURRENTQCNT",
    "M16HUB.QUE.M14TOM16.MESCURRENTQCNT", "M16HUB.QUE.M16TOM14.MESCURRENTQCNT",
    "M16HUB.QUE.M16TOM14A.MESCURRENTQCNT", "M16HUB.QUE.M16TOM14B.MESCURRENTQCNT",
    "M16HUB.QUE.MLUD.3F_TO_M16A_MLUD_AI_CMD",
    "M16HUB.QUE.OHT.CURRENTOHTQCNT", "M16HUB.QUE.OHT.OHTUTIL",
    "M16HUB.QUE.STB.3F_TO_M16A_3F_STB_CMD",
    "M16HUB.QUE.TIME.AVGTOTALTIME", "M16HUB.QUE.TIME.AVGTOTALTIME1MIN",
    "M16HUB.STRATE.ALL.FABSTORAGERATIO", "M16HUB.STRATE.STB.3F_STORAGE_UTIL",
    "M16HUB.STRATE.STK.STORAGERATIO",
    # ── M14 (41개) ──
    "M14.CNV.SENDFAB.TO_M16HUB_CURRENTQCNT",
    "M14.OHT.STATECNT.ABNORMAL", "M14.OHT.STATECNT.CONGESTED",
    "M14.OHT.STATECNT.HTSTOP", "M14.OHT.STATECNT.OBSANDBZSTOP",
    "M14.QUE.ABN.AOTRANSDELAY",
    "M14.QUE.ALL.3F_TO_HUB_JOB", "M14.QUE.ALL.3F_TO_HUB_JOB_ALT",
    "M14.QUE.ALL.CURRENTQCNT", "M14.QUE.ALL.CURRENTQCOMPLETED",
    "M14.QUE.ALL.CURRENTQCREATED", "M14.QUE.ALL.TOTALCNVCURRENTQCNT",
    "M14.QUE.ALL.TRANSPORT4MINOVERCNT", "M14.QUE.ALL.TRANSPORT4MINOVERRATIO",
    "M14.QUE.ALL.TRANSPORT4MINOVERTIMEAVG",
    "M14.QUE.CNV.3F_CNV_MAXCAPA",
    "M14.QUE.CNV.ALLTONORTHCNVCURRENTQCNT", "M14.QUE.CNV.ALLTOSOUTHCNVCURRENTQCNT",
    "M14.QUE.CNV.M14ATOM16ACURRNETQCNT", "M14.QUE.CNV.M14ATOM16CURRNETQCNT",
    "M14.QUE.CNV.M14ATONORTHCURRENTQCNT", "M14.QUE.CNV.M14ATOSOUTHCURRENTQCNT",
    "M14.QUE.CNV.NORTHCNVTOALLCURRENTQCNT",
    "M14.QUE.CNV.NORTHCNVTOM14TIME", "M14.QUE.CNV.NORTHCNVTOM14TIME1MIN",
    "M14.QUE.CNV.NORTHCURRENTQCNT",
    "M14.QUE.CNV.NORTHM14TOCNVTIME", "M14.QUE.CNV.NORTHM14TOCNVTIME1MIN",
    "M14.QUE.CNV.SOUTHCNVTOALLCURRENTQCNT",
    "M14.QUE.CNV.SOUTHCNVTOM14TIME", "M14.QUE.CNV.SOUTHCNVTOM14TIME1MIN",
    "M14.QUE.CNV.SOUTHCURRENTQCNT",
    "M14.QUE.CNV.SOUTHM14TOCNVTIME", "M14.QUE.CNV.SOUTHM14TOCNVTIME1MIN",
    "M14.QUE.LOAD.AVGLOADTIME", "M14.QUE.LOAD.AVGLOADTIME1MIN",
    "M14.QUE.OHT.3F_TO_HUB_CMD", "M14.QUE.OHT.OHTUTIL",
    "M14.QUE.SFAB.SENDTOM16",
    "M14.SORTER.ABN.CUSORTERWAITCOUNTOVER", "M14.SORTER.ABN.SORTERWAITCOUNTOVER",
    # ── M14B (42개) ──
    "M14B.LFT.4ABLD111.4F_TO_7F_CURRENTQCNT", "M14B.LFT.4ABLD111.7F_TO_4F_CURRENTQCNT",
    "M14B.LFT.4ABLD111.TOTAL_CURRENTQCNT",
    "M14B.LFT.4ABLD112.4F_TO_7F_CURRENTQCNT", "M14B.LFT.4ABLD112.7F_TO_4F_CURRENTQCNT",
    "M14B.LFT.4ABLD112.TOTAL_CURRENTQCNT",
    "M14B.LFT.4ABLD121.4F_TO_7F_CURRENTQCNT", "M14B.LFT.4ABLD121.7F_TO_4F_CURRENTQCNT",
    "M14B.LFT.4ABLD121.TOTAL_CURRENTQCNT",
    "M14B.LFT.4ABLD122.4F_TO_7F_CURRENTQCNT", "M14B.LFT.4ABLD122.7F_TO_4F_CURRENTQCNT",
    "M14B.LFT.4ABLD122.TOTAL_CURRENTQCNT",
    "M14B.LFT.4ABLD131.4F_TO_7F_CURRENTQCNT", "M14B.LFT.4ABLD131.7F_TO_4F_CURRENTQCNT",
    "M14B.LFT.4ABLD131.TOTAL_CURRENTQCNT",
    "M14B.LFT.4ABLD132.4F_TO_7F_CURRENTQCNT", "M14B.LFT.4ABLD132.7F_TO_4F_CURRENTQCNT",
    "M14B.LFT.4ABLD132.TOTAL_CURRENTQCNT",
    "M14B.LFT.SENDFAB.TO_M14A_CURRENTQCNT", "M14B.LFT.SENDFAB.TO_M16HUB_CURRENTQCNT",
    "M14B.OHT.ALERT.OHTMCPALARMCNT", "M14B.QUE.ABN.AOTRANSDELAY",
    "M14B.QUE.ALL.7F_TO_HUB_JOB", "M14B.QUE.ALL.7F_TO_HUB_JOB_ALT",
    "M14B.QUE.ALL.CURRENTQCNT", "M14B.QUE.ALL.CURRENTQCOMPLETED",
    "M14B.QUE.ALL.CURRENTQCREATED",
    "M14B.QUE.LFT.ALLTOLFTCURRENTQCNT", "M14B.QUE.LFT.LFTTOALLCURRENTQCNT",
    "M14B.QUE.LFT.M14BTOM16ACURRNETQCNT",
    "M14B.QUE.LOAD.AVGLOADTIME", "M14B.QUE.LOAD.AVGLOADTIME1MIN",
    "M14B.QUE.LOAD.CURRENTLOADQCNT",
    "M14B.QUE.OHT.7F_TO_HUB_CMD", "M14B.QUE.OHT.CURRENTOHTQCNT", "M14B.QUE.OHT.OHTUTIL",
    "M14B.QUE.SENDFAB.VERTICALQUEUECOUNT",
    "M14B.QUE.TIME.AVGTOTALTIME", "M14B.QUE.TIME.AVGTOTALTIME1MIN",
    "M14B.SORTER.ABN.CUSORTERWAITCOUNTOVER", "M14B.SORTER.ABN.SORTERWAITCOUNTOVER",
    "M14B.SORTER.ABN.SORTERWAITCOUNTOVER_B01",
    # ── M16A (37개) ──
    "M16A.LFT.SENDFAB.TO_M16B_CURRENTQCNT", "M16A.LFT.SENDFAB.TO_M16E_CURRENTQCNT",
    "M16A.LFT.SENDFAB.TO_M16HUB_CURRENTQCNT",
    "M16A.QUE.ABN.AOTRANSDELAY",
    "M16A.QUE.ALL.2F_TO_6F_JOB",
    "M16A.QUE.ALL.2F_TO_HUB_JOB", "M16A.QUE.ALL.2F_TO_HUB_JOB_ALT",
    "M16A.QUE.ALL.6F_TO_2F_JOB",
    "M16A.QUE.ALL.6F_TO_HUB_JOB", "M16A.QUE.ALL.6F_TO_HUB_JOB_ALT",
    "M16A.QUE.ALL.CURRENTQCNT", "M16A.QUE.ALL.CURRENTQCOMPLETED",
    "M16A.QUE.ALL.CURRENTQCREATED",
    "M16A.QUE.ALL.TRANSPORT4MINOVERCNT", "M16A.QUE.ALL.TRANSPORT4MINOVERRATIO",
    "M16A.QUE.ALL.TRANSPORT4MINOVERTIMEAVG",
    "M16A.QUE.CNV.ALLTONORTHCNVCURRENTQCNT", "M16A.QUE.CNV.ALLTOSOUTHCNVCURRENTQCNT",
    "M16A.QUE.CNV.M16ATOM14ACURRNETQCNT", "M16A.QUE.CNV.M16ATOM14BCURRNETQCNT",
    "M16A.QUE.CNV.M16TOM14ACURRNETQCNT", "M16A.QUE.CNV.M16TOM14BCURRNETQCNT",
    "M16A.QUE.CNV.NORTHCNVTOALLCURRENTQCNT", "M16A.QUE.CNV.SOUTHCNVTOALLCURRENTQCNT",
    "M16A.QUE.LFT.2F_LFT_MAXCAPA", "M16A.QUE.LFT.6F_LFT_MAXCAPA",
    "M16A.QUE.LFT.ALLTOLFTCURRENTQCNT", "M16A.QUE.LFT.LFTTOALLCURRENTQCNT",
    "M16A.QUE.LOAD.AVGFOUPLOADTIME", "M16A.QUE.LOAD.AVGLOADTIME1MIN",
    "M16A.QUE.LOAD.CURRENTLOADQCNT",
    "M16A.QUE.OHT.2F_TO_HUB_CMD", "M16A.QUE.OHT.6F_TO_HUB_CMD",
    "M16A.QUE.OHT.CURRENTOHTQCNT", "M16A.QUE.OHT.OHTUTIL",
    "M16A.SORTER.ABN.CUSORTERWAITCOUNTOVER", "M16A.SORTER.ABN.SORTERWAITCOUNTOVER",
    # ── M16B (16개) ──
    "M16B.LFT.SENDFAB.TO_M16A_CURRENTQCNT",
    "M16B.QUE.ABN.AOTRANSDELAY",
    "M16B.QUE.ALL.10F_TO_HUB_JOB",
    "M16B.QUE.ALL.CURRENTQCNT", "M16B.QUE.ALL.CURRENTQCOMPLETED",
    "M16B.QUE.ALL.CURRENTQCREATED",
    "M16B.QUE.ALL.TRANSPORT4MINOVERCNT", "M16B.QUE.ALL.TRANSPORT4MINOVERRATIO",
    "M16B.QUE.ALL.TRANSPORT4MINOVERTIMEAVG",
    "M16B.QUE.LOAD.AVGFOUPLOADTIME", "M16B.QUE.LOAD.AVGLOADTIME1MIN",
    "M16B.QUE.LOAD.CURRENTLOADQCNT",
    "M16B.QUE.OHT.CURRENTOHTQCNT", "M16B.QUE.OHT.OHTUTIL",
    "M16B.SORTER.ABN.CUSORTERWAITCOUNTOVER", "M16B.SORTER.ABN.SORTERWAITCOUNTOVER",
    # ── M16 (11개) ──
    "M16.CNV.SENDFAB.TO_M16WT_CURRENTQCNT",
    "M16.QUE.SFAB.COMPLETEQUEUETOTAL", "M16.QUE.SFAB.COMPLETETOM10", "M16.QUE.SFAB.COMPLETETOM14",
    "M16.QUE.SFAB.RECEIVEQUEUETOTAL",
    "M16.QUE.SFAB.RETURNQUEUETOTAL", "M16.QUE.SFAB.RETURNTOM10", "M16.QUE.SFAB.RETURNTOM14",
    "M16.QUE.SFAB.SENDQUEUETOTAL", "M16.QUE.SFAB.SENDTOM10", "M16.QUE.SFAB.SENDTOM14",
    # ── M16_PKT (4개) ──
    "M16_PKT.OHT.ALERT.OHTMCPALARMCNT", "M16_PKT.QUE.ABN.AOTRANSDELAY",
    "M16_PKT.QUE.OHT.OHTUTIL", "M16_PKT.QUE.TIME.AVGTOTALTIME1MIN",
    # ── M16_WT (4개) ──
    "M16_WT.OHT.ALERT.OHTMCPALARMCNT", "M16_WT.QUE.ABN.AOTRANSDELAY",
    "M16_WT.QUE.OHT.OHTUTIL", "M16_WT.QUE.TIME.AVGTOTALTIME1MIN",
]

# ============================================================
# ★ 룰별 영역 → raw 풀네임 (hubroom_predictor.py 와 동일)
# ============================================================
RA_COL = {
    'M16HUB':  'M16HUB.QUE.TIME.AVGTOTALTIME1MIN',
    'M14':     'M14.QUE.LOAD.AVGLOADTIME1MIN',
    'M14B':    'M14B.QUE.TIME.AVGTOTALTIME1MIN',
    'M16A':    'M16A.QUE.LOAD.AVGLOADTIME1MIN',
    'M16B':    'M16B.QUE.LOAD.AVGLOADTIME1MIN',
    'M16_PKT': 'M16_PKT.QUE.TIME.AVGTOTALTIME1MIN',
    'M16_WT':  'M16_WT.QUE.TIME.AVGTOTALTIME1MIN',
}
RB_COL = {
    'M16HUB': 'M16HUB.QUE.M14TOM16.MESCURRENTQCNT',
    'M14':    'M14.QUE.ALL.3F_TO_HUB_JOB',
    'M14B':   'M14B.QUE.ALL.7F_TO_HUB_JOB',
    'M16A':   'M16A.QUE.ALL.6F_TO_HUB_JOB',
    'M16B':   'M16B.QUE.ALL.10F_TO_HUB_JOB',
    'M16':    'M16.QUE.SFAB.SENDQUEUETOTAL',
}
RD_OHT_COL = {
    'M16HUB': 'M16HUB.QUE.OHT.OHTUTIL',
    'M14':    'M14.QUE.OHT.OHTUTIL',
    'M14B':   'M14B.QUE.OHT.OHTUTIL',
    'M16A':   'M16A.QUE.OHT.OHTUTIL',
    'M16B':   'M16B.QUE.OHT.OHTUTIL',
}
RD_FAB_COL = 'M16HUB.STRATE.ALL.FABSTORAGERATIO'
RD_STB_COL = 'M16HUB.STRATE.STB.3F_STORAGE_UTIL'
SLA_COL = {
    'M16HUB': 'M16HUB.QUE.ALL.TRANSPORT4MINOVERRATIO',
    'M14':    'M14.QUE.ALL.TRANSPORT4MINOVERRATIO',
    'M14B':   'M14B.QUE.ALL.TRANSPORT4MINOVERRATIO',
    'M16A':   'M16A.QUE.ALL.TRANSPORT4MINOVERRATIO',
    'M16B':   'M16B.QUE.ALL.TRANSPORT4MINOVERRATIO',
}
SORTER_COL = {
    'M14':    'M14.SORTER.ABN.SORTERWAITCOUNTOVER',
    'M14B':   'M14B.SORTER.ABN.SORTERWAITCOUNTOVER',
    'M16A':   'M16A.SORTER.ABN.SORTERWAITCOUNTOVER',
    'M16B':   'M16B.SORTER.ABN.SORTERWAITCOUNTOVER',
    'M16HUB': 'M16HUB.SORTER.ABN.SORTERWAITCOUNTOVER',
}

# R-C' 리프터 (M16HUB.LFT.* 들의 추세 분석 → 단일 컬럼 아님)
RC_REPRESENTATIVE = 'M16HUB.LFT (리프터)'

# ============================================================
# ★ 발동이벤트.csv 축약 컬럼 ↔ raw 풀네임 (양방향)
# ============================================================
EVT_TO_RAW = {
    # 반송시간 R-A
    'M16HUB_ra': RA_COL['M16HUB'],
    'M14_ra':    RA_COL['M14'],
    'M14B_ra':   RA_COL['M14B'],
    'M16A_ra':   RA_COL['M16A'],
    'M16B_ra':   RA_COL['M16B'],
    # R-D 저장율 / OHT
    'M16HUB_rd_fab':    RD_FAB_COL,
    'M16HUB_stb_util':  RD_STB_COL,
    'M14_rd_oht':       RD_OHT_COL['M14'],
    'M14B_rd_oht':      RD_OHT_COL['M14B'],
    'M16A_rd_oht':      RD_OHT_COL['M16A'],
    'M16B_rd_oht':      RD_OHT_COL['M16B'],
    # SLA
    'sla_M16HUB': SLA_COL['M16HUB'],
    'sla_M14':    SLA_COL['M14'],
    'sla_M14B':   SLA_COL['M14B'],
    'sla_M16A':   SLA_COL['M16A'],
    'sla_M16B':   SLA_COL['M16B'],
    # Sorter
    'sorter_M14':    SORTER_COL['M14'],
    'sorter_M14B':   SORTER_COL['M14B'],
    'sorter_M16A':   SORTER_COL['M16A'],
    'sorter_M16B':   SORTER_COL['M16B'],
    'sorter_M16HUB': SORTER_COL['M16HUB'],
    # R-C' (특수 — 단일 raw 컬럼 없음, 대표명)
    'M16HUB_rev_count': RC_REPRESENTATIVE,
}
RAW_TO_EVT = {v: k for k, v in EVT_TO_RAW.items()}


# ============================================================
# ★ 한글 친화 라벨 (그래프에 큰 글씨로 표시)
# ============================================================
def friendly_label(evt_col):
    if evt_col.endswith('_ra'):
        a = evt_col.replace('_ra', ''); return f"{a} 반송시간 (분)"
    if evt_col == 'M16HUB_rd_fab':    return "M16HUB FAB 저장율 (%)"
    if evt_col == 'M16HUB_stb_util':  return "M16HUB STB 저장율 (%)"
    if evt_col == 'M16HUB_rev_count': return "M16HUB 리프터 (대)"
    if evt_col.endswith('_rd_oht'):
        a = evt_col.replace('_rd_oht', ''); return f"{a} OHT 가동률 (%)"
    if evt_col.startswith('sla_'):
        a = evt_col.replace('sla_', ''); return f"{a} 4분초과율 (%)"
    if evt_col.startswith('sorter_'):
        a = evt_col.replace('sorter_', ''); return f"{a} Sorter 대기 (LOT)"
    return evt_col


# ============================================================
# ★ reason 텍스트 → 발동 컬럼 (evt_col, raw_full, area, rule) 추출
#
# reason 예시:
#   "hot_area=M16HUB; S3확정; 발동: M16HUB[R-A'(AVGTOTALTIME1MIN=6.34분),
#    R-D(FAB저장=0.0%,STB=100.0%)]; M16B[R-D(OHT=98.7%),SLA(47.7%4분초과)]"
# ============================================================
_AREA_RE = re.compile(r"(M16HUB|M14B|M14|M16A|M16B|M16_PKT|M16_WT|M16)\[([^\]]+)\]")


def parse_reason_pairs(reason):
    """발동이벤트 reason → [(evt_col, raw_full, area, rule)] 발동 컬럼 추출.

    동일 컬럼 중복 제거. 영역 순서 유지.
    """
    out = []
    seen = set()

    def add(evt_col, raw_full, area, rule):
        if evt_col in seen: return
        seen.add(evt_col)
        out.append((evt_col, raw_full, area, rule))

    for m in _AREA_RE.finditer(reason or ''):
        area, body = m.group(1), m.group(2)
        # R-A' / R-A_sus — AVGTOTALTIME1MIN / AVGLOADTIME1MIN
        if "AVGTOTALTIME1MIN" in body or "AVGLOADTIME1MIN" in body or "R-A'" in body or "R-A_sus" in body:
            evt = f"{area}_ra"
            if evt in EVT_TO_RAW:
                add(evt, EVT_TO_RAW[evt], area, "R-A")
        # R-D M16HUB FAB / STB
        if area == 'M16HUB' and ('FAB저장' in body or 'FABSTORAGE' in body):
            add('M16HUB_rd_fab', RD_FAB_COL, area, "R-D(FAB)")
        if area == 'M16HUB' and 'STB=' in body:
            add('M16HUB_stb_util', RD_STB_COL, area, "R-D(STB)")
        # R-D OHT (M14/M14B/M16A/M16B)
        if ('OHT=' in body or 'OHTUTIL' in body) and area in RD_OHT_COL and area != 'M16HUB':
            evt = f"{area}_rd_oht"
            add(evt, RD_OHT_COL[area], area, "R-D(OHT)")
        # SLA
        if ('SLA(' in body or 'TRANSPORT4MIN' in body) and area in SLA_COL:
            evt = f"sla_{area}"
            add(evt, SLA_COL[area], area, "SLA")
        # Sorter
        if ('Sorter(' in body or 'SORTERWAIT' in body) and area in SORTER_COL:
            evt = f"sorter_{area}"
            add(evt, SORTER_COL[area], area, "Sorter")
        # R-C' 리프터 (M16HUB 전용) — reason 키워드 매칭만 유지
        if area == 'M16HUB' and '역증가' in body:
            add('M16HUB_rev_count', RC_REPRESENTATIVE, area, "R-C'")
    return out


# ============================================================
# ★ 사건단위 relation 텍스트 → 발동 컬럼 추출
#
# relation 예시:
#   "[M16HUB R-A'] M16HUB.QUE.TIME.AVGTOTALTIME1MIN=6.34분 (기준 5.0분) |
#    [M16HUB R-D] FABSTORAGERATIO=92.3% (기준 90%)"
# → relation 은 raw 풀네임 직접 포함
# ============================================================
_RAW_COL_RE = re.compile(r"\b([A-Z][A-Z0-9_]+(?:\.[A-Z0-9_]+){2,})\b")


def parse_relation_pairs(relation):
    """사건단위 relation → [(evt_col, raw_full, area, rule)].

    relation 에는 raw 풀네임이 직접 들어 있어 텍스트 그대로 추출.
    """
    out = []
    seen = set()
    text = relation or ''
    # raw 풀네임 직접 추출
    for raw in _RAW_COL_RE.findall(text):
        if raw in RAW_TO_EVT and raw not in seen:
            seen.add(raw)
            evt = RAW_TO_EVT[raw]
            area = raw.split('.')[0]
            # 룰 식별 (텍스트 패턴)
            rule = "?"
            for rid in ("R-A'", "R-A_sus", "R-A", "R-B_fast", "R-B", "R-C'", "R-C",
                        "R-D", "SLA", "Sorter", "MAXCAPA"):
                if f"[{area} {rid}]" in text or rid in text:
                    rule = rid; break
            out.append((evt, raw, area, rule))
    # 리프터 (한글 키워드 — relation 안의 '역증가'/'감소' 텍스트만 매칭에 사용)
    if '리프터' in text and '역증가' in text and 'M16HUB_rev_count' not in seen:
        seen.add('M16HUB_rev_count')
        out.append(('M16HUB_rev_count', RC_REPRESENTATIVE, 'M16HUB', "R-C'"))
    return out


if __name__ == '__main__':
    # 자체 테스트
    s = ("hot_area=M16HUB; S3확정; 발동: "
         "M16HUB[R-A'(AVGTOTALTIME1MIN=6.34분),R-D(FAB저장=0.0%,STB=100.0%)]; "
         "M16B[R-D(OHT=98.7%),SLA(47.7%4분초과)]")
    print("reason →")
    for evt, raw, area, rule in parse_reason_pairs(s):
        print(f"   [{area} {rule}] {evt} ← {raw}")
    r = ("[M16HUB R-A'] M16HUB.QUE.TIME.AVGTOTALTIME1MIN=6.34분 (기준 5.0분) | "
         "[M16HUB R-D] M16HUB.STRATE.ALL.FABSTORAGERATIO=92.3% (기준 90%) | "
         "[M16HUB R-C'] 리프터 3개 (기준 2)")
    print("relation →")
    for evt, raw, area, rule in parse_relation_pairs(r):
        print(f"   [{area} {rule}] {evt} ← {raw}")
    print(f"\nRAW 265 / EVT_TO_RAW {len(EVT_TO_RAW)} / RAW_TO_EVT {len(RAW_TO_EVT)}")
